select * from customer limit  20

--Q1. What is the total revenue generated by male vs.female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender


--02. Which customers used a discount but still spent more than the average purchase amount? 03. Which are the top 5 products with the highest average review rating?
select customer_id, purchase_amount
from customer
where disscount)applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount from customer))

--03.Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(avg(review_rating::numeric),2) as "average product rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE LOWER(shipping_type) IN ('standard', 'express')
GROUP BY shipping_type;

--Q5.  subscribed customer's spend more? Compare average spend and total revenue between subscribers  and non-subscribers?
select subscription_status,
count(customer_id) as total_customers,
Round(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with ufchases with discounts applied?
select item_purchased,
ROUND(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end )/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


--07. Segment customers into New, Returning, and Loyal based on their total number of previos purchases and show the count of each segment ?
with customer_type as (
select customer_id,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--08. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts;

--09.Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10.what is the revenue contribution of  each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;